# Netlify configuration for Garment ERP PWA

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "false"

[functions]
  directory = "netlify/functions"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables for production (main branch)
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "https://garment-erp-nepal.netlify.app/api"
  JWT_SECRET = "garment-erp-jwt-secret-prod"
  TOKEN_EXPIRY = "24h"
  BUNDLE_CACHE_TTL = "300"
  PUSH_NOTIFICATION_ENABLED = "true"

# Environment variables for staging (staging branch)
[context.staging.environment]
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_API_URL = "https://staging--garment-erp-nepal.netlify.app/api"
  JWT_SECRET = "garment-erp-jwt-secret-staging"
  TOKEN_EXPIRY = "24h"
  BUNDLE_CACHE_TTL = "60"
  PUSH_NOTIFICATION_ENABLED = "true"

# Environment variables for development (develop branch)
[context.develop.environment]
  REACT_APP_ENVIRONMENT = "development"
  REACT_APP_API_URL = "https://dev--garment-erp-nepal.netlify.app/api"
  JWT_SECRET = "garment-erp-jwt-secret-dev"
  TOKEN_EXPIRY = "24h"
  BUNDLE_CACHE_TTL = "30"
  PUSH_NOTIFICATION_ENABLED = "true"

# Environment variables for branch deploys (feature branches)
[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "development"
  REACT_APP_API_URL = "https://deploy-preview--garment-erp-nepal.netlify.app/api"
  JWT_SECRET = "garment-erp-jwt-secret-preview"
  TOKEN_EXPIRY = "24h"
  BUNDLE_CACHE_TTL = "10"
  PUSH_NOTIFICATION_ENABLED = "false"

# Security and CORS headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# PWA configuration
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

# Static file caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


# SPA routing - catch-all for React Router (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200