// Demo Data Configuration
// Sample data for development and testing

// Demo Users for Development
export const DEMO_USERS = {
  OPERATORS: [
    {
      id: "op001",
      username: "ram.singh",
      password: "password123",
      name: "ram",
      nameEn: "Ram",
      role: "operator",
      employeeId: "EMP001",
      assignedMachines: ["overlock-1"],
      machineType: "overlock",
      skills: ["overlock-advanced"],
      status: "active",
      department: "sewing",
      shift: "day",
      hourlyRate: 250,
      active: true,
      productivity: {
        totalBundles: 45,
        completedBundles: 43,
        averageTime: 25,
        qualityScore: 95
      }
    },
    {
      id: "op002",
      username: "ashika.devi",
      password: "password123",
      name: "ashika",
      nameEn: "Ashika",
      role: "operator",
      employeeId: "EMP002",
      assignedMachines: ["overlock-2"],
      machineType: "overlock",
      skills: ["overlock-intermediate"],
      status: "active",
      department: "sewing",
      shift: "day",
      hourlyRate: 220,
      active: true,
      productivity: {
        totalBundles: 38,
        completedBundles: 35,
        averageTime: 28,
        qualityScore: 92
      }
    },
    {
      id: "op003",
      username: "bimala.thapa",
      password: "password123",
      name: "bimala",
      nameEn: "Bimala",
      role: "operator",
      employeeId: "EMP003",
      assignedMachines: ["overlock-3"],
      machineType: "overlock",
      skills: ["overlock-intermediate"],
      status: "active",
      department: "sewing",
      shift: "day",
      hourlyRate: 230,
      active: true,
      productivity: {
        totalBundles: 41,
        completedBundles: 39,
        averageTime: 26,
        qualityScore: 94
      }
    },
    {
      id: "op004",
      username: "govin.singh",
      password: "password123",
      name: "govin",
      nameEn: "Govin",
      role: "operator",
      employeeId: "EMP004",
      assignedMachines: ["flatlock-1"],
      machineType: "flatlock",
      skills: ["flatlock-advanced"],
      status: "active",
      department: "sewing",
      shift: "day",
      hourlyRate: 260,
      active: true,
      productivity: {
        totalBundles: 35,
        completedBundles: 33,
        averageTime: 30,
        qualityScore: 96
      }
    },
    {
      id: "op005",
      username: "siru.maharjan",
      password: "password123",
      name: "siru",
      nameEn: "Siru",
      role: "operator",
      employeeId: "EMP005",
      assignedMachines: ["single-needle-1"],
      machineType: "single-needle",
      skills: ["single-needle-intermediate"],
      status: "active",
      department: "sewing",
      shift: "day",
      hourlyRate: 200,
      active: true,
      productivity: {
        totalBundles: 50,
        completedBundles: 48,
        averageTime: 22,
        qualityScore: 90
      }
    }
  ],
  SUPERVISORS: [
    {
      id: "sup001",
      username: "supervisor",
      password: "super123",
      name: "Shyam Pokharel",
      nameEn: "Shyam Pokharel",
      role: "supervisor",
      employeeId: "SUP001",
      assignedLine: "line-1",
      department: "sewing",
      shift: "day",
      status: "active",
      active: true,
      permissions: ["all_view", "work_assign", "quality_manage", "report_view"],
      hourlyRate: 400
    },
    {
      id: "sup002",
      username: "maya.supervisor",
      password: "super123", 
      name: "Maya Gurung",
      nameEn: "Maya Gurung",
      role: "supervisor",
      employeeId: "SUP002",
      assignedLine: "line-2", 
      department: "sewing",
      shift: "day",
      status: "active",
      active: true,
      permissions: ["all_view", "work_assign", "quality_manage", "report_view"],
      hourlyRate: 380
    }
  ],
  MANAGEMENT: [
    {
      id: "mgmt001",
      username: "management",
      password: "mgmt123",
      name: "Management User",
      nameEn: "Management User",
      role: "management",
      department: "administration",
      permissions: ["admin", "all_view", "all_manage", "reports", "analytics"],
    },
  ],
};

// Sample Bundles for Development
export const SAMPLE_BUNDLES = [
  {
    id: "B001-85-BL-XL",
    bundleNumber: "B001",
    article: 8085,
    articleName: "Polo T-Shirt",
    color: "Blue",
    colorCode: "BL",
    sizes: ["XL"],
    quantity: 50,
    rate: 2.5,
    totalValue: 125,
    priority: "high",
    dueDate: "2024-01-15",
    status: "pending",
    machineType: "overlock",
    currentOperation: "shoulderJoin",
    assignedOperator: null,
    assignedLine: "line-1",
    estimatedTime: 60,
  },
  {
    id: "B002-33-GR-26",
    bundleNumber: "B002",
    article: 1020,
    articleName: "Ladies Pants",
    color: "Green",
    colorCode: "GR",
    sizes: ["26"],
    quantity: 30,
    rate: 3.0,
    totalValue: 90,
    priority: "medium",
    dueDate: "2024-01-20",
    status: "pending",
    machineType: "flatlock",
    currentOperation: "sideSeam",
    assignedOperator: null,
    assignedLine: "line-1",
    estimatedTime: 45,
  },
  {
    id: "B003-01-WH-4XL",
    bundleNumber: "B003",
    article: 9001,
    articleName: "Plus Size Shirt",
    color: "White",
    colorCode: "WH",
    sizes: ["4XL"],
    quantity: 25,
    rate: 4.0,
    totalValue: 100,
    priority: "medium",
    dueDate: "2024-01-25",
    status: "pending",
    machineType: "singleNeedle",
    currentOperation: "collar",
    assignedOperator: null,
    assignedLine: "line-1",
    estimatedTime: 90,
  },
];

export default { DEMO_USERS, SAMPLE_BUNDLES };